[target]
programs= ALROShell
units= Analizador Comandos Utilidades ALR

[compiler]
version= 2.4.0

[package]
name= ALROShell
version= 2.0

[default]
fpcdir= ../..

[clean]
units= Analizador Comandos Utilidades ALR

[install]
datadir= /usr/share/man/man1/
files= ../Documentacion/ALROShell.1.gz


