[target]
programs= ALROShell
units= Analizador Comandos Utilidades ALR

[compiler]
version= 2.4.0

[package]
name= ALROShell
version= 2.0

[default]
fpcdir= ../..

[clean]
files = units/


[install]
datadir= /usr/share/man/man1/
files= ../Documentacion/ALROShell.1.gz

[rules]

clean = true

.PHONY : clean
clean : 
	rm -r -f units
